services:
  - type: web
    name: max-overtime
    runtime: python
    buildCommand: pip install -e .
    startCommand: gunicorn run:server --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
